### ISSUE TITLE
Indigo Release 04-2016

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/care-o-bot#22]
Tracking the related PRs to rosdistro:
- [x] [cob_android](https://github.com/ipa320/cob_android): `0.1.2-0` https://github.com/ros/rosdistro/pull/10956
- [x] [cob_calibration_data](https://github.com/ipa320/cob_calibration_data): `0.6.5-0` https://github.com/ros/rosdistro/pull/10953
- [x] [cob_command_tools](https://github.com/ipa320/cob_command_tools): `0.6.4-0` https://github.com/ros/rosdistro/pull/10957
- [x] [cob_common](https://github.com/ipa320/cob_common): `0.6.5-0` https://github.com/ros/rosdistro/pull/10954
- [x] [cob_control](https://github.com/ipa320/cob_control): `0.6.11-0` https://github.com/ros/rosdistro/pull/10958
- [x] [cob_driver](https://github.com/ipa320/cob_driver): `0.6.7-0` https://github.com/ros/rosdistro/pull/10976
- [x] [cob_environments](https://github.com/ipa320/cob_environments): `0.6.3-0` https://github.com/ros/rosdistro/pull/10955
- [x] [cob_extern](https://github.com/ipa320/cob_extern): `0.6.4-0` https://github.com/ros/rosdistro/pull/10951
- [x] [cob_gazebo_plugins](https://github.com/ipa320/cob_gazebo_plugins): `0.6.4-0` https://github.com/ros/rosdistro/pull/10960
- [x] [cob_manipulation](https://github.com/ipa320/cob_manipulation): `0.6.4-0` https://github.com/ros/rosdistro/pull/10964
- [x] [cob_navigation](https://github.com/ipa320/cob_navigation): `0.6.4-0` https://github.com/ros/rosdistro/pull/10965
- [x] [cob_perception_common](https://github.com/ipa320/cob_perception_common): `0.6.7-0` https://github.com/ros/rosdistro/pull/10961
- [x] [cob_robots](https://github.com/ipa320/cob_robots): `0.6.5-0` https://github.com/ros/rosdistro/pull/10968
- [x] [cob_simulation](https://github.com/ipa320/cob_simulation): `0.6.5-0` https://github.com/ros/rosdistro/pull/10963
- [x] [cob_substitute](https://github.com/ipa320/cob_substitute): `0.6.3-0` https://github.com/ros/rosdistro/pull/10952
- [ ] [~~ros_canopen~~](https://github.com/ros-industrial/ros_canopen): :point_right: will be done by @ipa-mdl
- [x] [schunk_modular_robotics](https://github.com/ipa320/schunk_modular_robotics): `0.6.7-0` https://github.com/ros/rosdistro/pull/10962
- [x] [universal_robot](https://github.com/ros-industrial/universal_robot): `1.1.6-0` https://github.com/ros/rosdistro/pull/10950
- [x] [care-o-bot](https://github.com/ipa320/care-o-bot): `0.6.5-0` https://github.com/ros/rosdistro/pull/10969

**Comment by ipa-fxm** [comment]
I could not release
 - `cob_driver`
 - `cob_robots`
 - `care-o-bot` 
due to missing rosdep keys

**Comment by ipa-fxm** [comment]
http://repositories.ros.org/status_page/ros_indigo_default.html?q=cob

**Comment by ipa-fxm** [comment]
all green already - waiting for sync!

**Comment by ipa-fxm** [comment]
The following repositories could be released for __ROS Jade__ (using the respective `indigo_dev` branches - without modification):
 - cob_android
 - cob_calibration_data
 - cob_command_tools
 - cob_common
 - cob_control
 - cob_driver
 - cob_environments
 - cob_extern
 - cob_perception_common
 - cob_substitute
 - schunk_modular_robotics

(I created update `jade_dev`/`jade-devel` branches for them on my forks)

For `ros_canopen`, the version using @ipa-mdl's `canSwitch`-API needs to be released

`cob_driver` cannot be released as `cob_elmo_homing` depends on `canopen_402`

**Comment by ipa-fmw** [comment]
we'll not release for Jade but wait for Kinetic Kame (to come in Mai 2016), which is a LTS again.

**Comment by ipa-fxm** [comment]
This was just a summary for Jade to see what's there...
For Kinetic even more packages are missing!

**Comment by ipa-fxm** [comment]
I guess we will want to re-release a view packages some time soon:
 - cob_driver
 - cob_robots
 - cob_manipulation
__This list is not complete!__

**Comment by ipa-mig** [comment]
Are there any plans for another release soon? Should we close this?

**Comment by ipa-fmw** [comment]
as the set of release packages is fine (as far as I know), I would close this and open a new issue if a new release is needed
