### ISSUE TITLE
Kinetic Release Preparations

### ISSUE THREAD

**Issue by ipa-mig** [ipa320/care-o-bot#28]
**Tested repositories**
- [x] [cob_android](https://github.com/ipa320/cob_android)
- [x] [cob_calibration_data](https://github.com/ipa320/cob_calibration_data)
- [x] [cob_command_tools](https://github.com/ipa320/cob_command_tools)
- [x] [cob_common](https://github.com/ipa320/cob_common)
- [x] [cob_control](https://github.com/ipa320/cob_control)
- [x] [cob_driver](https://github.com/ipa320/cob_driver)
- [x] [cob_environments](https://github.com/ipa320/cob_environments)
- [x] [cob_extern](https://github.com/ipa320/cob_extern)
- [x] [cob_gazebo_plugins](https://github.com/ipa320/cob_gazebo_plugins)
- [x] [cob_manipulation](https://github.com/ipa320/cob_manipulation)
- [x] [cob_navigation](https://github.com/ipa320/cob_navigation)
- [x] [cob_perception_common](https://github.com/ipa320/cob_perception_common)
- [x] [cob_simulation](https://github.com/ipa320/cob_simulation)
- [x] [cob_substitute](https://github.com/ipa320/cob_substitute)
- [x] [schunk_modular_robotics](https://github.com/ipa320/schunk_modular_robotics)

**Not Tested**
- [x] [cob_robots](https://github.com/ipa320/cob_robots)
- [x] [care-o-bot](https://github.com/ipa320/care-o-bot)

(Note that those packages have not been tested for functionality!)

**Comment by ipa-mig** [comment]
@ipa-fmw @ipa-nhg @ipa-bnm

**Comment by ipa-bnm** [comment]
great overview :+1: thx

**Comment by mathias-luedtke** [comment]
`cob_omni_drive_controller` is part of `cob_control` and is not related to `ros_canopen`, not sure if it can be built due to `ros_control` API changes.

**Comment by mgruhler** [comment]
@ipa-bnm remember this issue, if you are working through the kinetic migration stuff :-)

**Comment by benmaidel** [comment]
@ipa-mig great, thank you!

**Comment by mathias-luedtke** [comment]
`ros_canopen (jade-devel)` works on kinetic as well.
Release is still pending.

**Comment by benmaidel** [comment]
uncomplete rosinstall for kinetic: https://gist.github.com/ipa-bnm/b1b748b94fb88d78fec00dbf37cb2cf1

**Comment by mgruhler** [comment]
@ipa-bnm @ipa-fxm AFAIK, all compiles by now in kinetic, right? Should the list above be updated?

**Comment by fmessmer** [comment]
No, not everything compiles...I'm working on it...will post as soon as I have the overall-overview...
So far, I only can tell about cob_bringup. I haven't tested simulation, navigation, perception, msh...

**Comment by mgruhler** [comment]
Have you synced with @ipa-bnm ? I'm not sure what works for him, but just to make sure to not have double effort...

**Comment by benmaidel** [comment]
@ipa-mig All kinetic_dev branches I've created are compile able. But as we've decided to switch back to `indigo_dev` branches there is a bit more to do. Also the simulation of cob4 was running on my machine, just the controllers made problems.

**Comment by mgruhler** [comment]
I'll close this now, as, afair, all packages can be compiled now. @ipa-bnm @ipa-fxm

**Comment by fmessmer** [comment]
Well, not all changes needed to compile have made it back to ipa320 branches (indigo_dev/kinetic_dev) yet...and kinetic release is still some way to go...

**Comment by mgruhler** [comment]
True, but what I had in mind with this issue is now fixed. I think it would make more sense to open another issue where we track which package has been checked/changed to work with both, indigo and kinetic, and which require a special branch.
