### ISSUE TITLE
update travis to use industrial_ci

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/care-o-bot#36]
should be done for
### bringup packages
 - cob_android (https://github.com/ipa320/cob_android/pull/25)
 - cob_calibration_data (https://github.com/ipa320/cob_calibration_data/pull/122)
 - cob_command_tools (https://github.com/ipa320/cob_command_tools/pull/183)
 - cob_common (https://github.com/ipa320/cob_common/pull/213)
 - cob_control (indigo: https://github.com/ipa320/cob_control/pull/145; kinetic: https://github.com/ipa320/cob_control/pull/146)
 - cob_docking (https://github.com/ipa320/cob_docking/pull/34)
 - cob_driver (https://github.com/ipa320/cob_driver/pull/323)
 - cob_environments (https://github.com/ipa320/cob_environments/pull/119)
 - cob_extern (https://github.com/ipa320/cob_extern/pull/79)
 - cob_gazebo_plugins (indigo: https://github.com/ipa320/cob_gazebo_plugins/pull/26; kinetic: https://github.com/ipa320/cob_gazebo_plugins/pull/27)
 - cob_hand (https://github.com/ipa320/cob_hand/pull/14)
 - cob_manipulation (indigo: https://github.com/ipa320/cob_manipulation/pull/102; kinetic: https://github.com/ipa320/cob_manipulation/pull/103)
 - cob_navigation (https://github.com/ipa320/cob_navigation/pull/83)
 - cob_perception_common (https://github.com/ipa320/cob_perception_common/pull/76)
 - cob_robots (https://github.com/ipa320/cob_robots/pull/626)
 - cob_simulation (https://github.com/ipa320/cob_simulation/pull/140)
 - cob_substitute (https://github.com/ipa320/cob_substitute/pull/44)
 - cob_supported_robots (https://github.com/ipa320/cob_supported_robots/pull/2)
 - schunk_modular_robotics (https://github.com/ipa320/schunk_modular_robotics/pull/184)
 - schunk_robots (https://github.com/ipa320/schunk_robots/pull/75)
 - sick_flexisoft (https://github.com/ipa320/sick_flexisoft/pull/38)

### msh packages
 - cob_people_perception (https://github.com/ipa320/cob_people_perception/pull/63)
 - ipa_navigation (https://github.com/ipa320/ipa_navigation/pull/179)
 - ipa_navigation_common (indigo: https://github.com/ipa320/ipa_navigation_common/pull/109; kinetic: https://github.com/ipa320/ipa_navigation_common/pull/113)
 - ipa_navigation_driver (https://github.com/ipa320/ipa_navigation_driver/pull/35)
 - ipa_navigation_localization (https://github.com/ipa320/ipa_navigation_localization/pull/184)
 - ipa_navigation_perception (https://github.com/ipa320/ipa_navigation_perception/pull/26)
 - ipa_navigation_planning (https://github.com/ipa320/ipa_navigation_planning/pull/156)
 - ipa_navigation_sandbox (https://github.com/ipa320/ipa_navigation_sandbox/pull/204)
 - cob_karto (add by @ipa-mig)
 - msh (https://github.com/ipa320/msh/pull/671)
 - msh_common (https://github.com/ipa320/msh_common/pull/42)
 - msh_gui (https://github.com/ipa320/msh_gui/pull/10)
 - msh_voice_control (https://github.com/ipa320/msh_voice_control/pull/145)

### optional packages
 - cob_object_perception (https://github.com/ipa320/cob_object_perception/pull/46)
 - cob_environment_perception

**Comment by souravran** [comment]
all the above mentioned packages have been updated

**Comment by fmessmer** [comment]
I guess I will do another release for indigo in order to get the rosdeps right for our new packages:
 - cob_supported_robots
 - cob_helper_tools

**Comment by fmessmer** [comment]
Also, as we are now testing all repos with `catkin build` instead of `catkin_make` we should recommend everybody to compile their workspace using `catkin build` rather than `catkin_make`

That would also require some changes in the setup scripts @ipa-nhg @ipa-fmw...

**Comment by fmessmer** [comment]
@ipa-fmw @ipa-nhg @ipa-bnm @ipa-mig @ipa-mdl

https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Aipa320+Multi+distro+travis

I created most multi-distro-travis PRs to the bringup-packages....
There still are a few issues to resolve, e.g.
 - ~~https://github.com/ipa320/cob_control/pull/145#issuecomment-284222846~~
 - https://github.com/ipa320/cob_driver/pull/323#issuecomment-284223381
 - https://github.com/ipa320/cob_extern/pull/79
 - https://github.com/ipa320/schunk_modular_robotics/pull/184#issuecomment-284232192

Those need to be resolved before preparing ~~cob_robots, cob_simulation~~ and all other packages from the list above... (**Help appreciated!**)

So far, it seems that we only need a `kinetic_dev`-branch for 
 - cob_control
 - cob_gazebo_plugins
 - cob_manipulation

**Comment by fmessmer** [comment]
that glass of single malt is well deserved :tumbler_glass: 
finalizing during upcoming week...
