### ISSUE TITLE
Indigo/Kinetic Release 07-2017

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/care-o-bot#42]
Tracking the related PRs to rosdistro:
:warning: = not dual-distro compatible, i.e. `indigo_dev` for Indigo and `kinetic_dev` for Kinetic

- [x] [cob_android](https://github.com/ipa320/cob_android): @ipa-jcl `0.1.3-0` indigo: https://github.com/ros/rosdistro/pull/15548 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15655 :white_check_mark:
- [x] [cob_calibration_data](https://github.com/ipa320/cob_calibration_data): @ipa-rmb `0.6.7-0` indigo: https://github.com/ros/rosdistro/pull/15540 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15542 :white_check_mark:
- [x] [cob_command_tools](https://github.com/ipa320/cob_command_tools):  @ipa-flg-pb `0.6.6-0` indigo: https://github.com/ros/rosdistro/pull/15538 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15594 :white_check_mark:
- [x] [cob_common](https://github.com/ipa320/cob_common): @ipa-flg-pb `0.6.7-0` indigo: https://github.com/ros/rosdistro/pull/15531 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15532 :white_check_mark:
- [x] [cob_control](https://github.com/ipa320/cob_control): :warning: @ipa-rmb `0.6.15-0, 0.7.0-0` indigo: https://github.com/ros/rosdistro/pull/15546 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15560 :white_check_mark:
- [x] [cob_driver](https://github.com/ipa320/cob_driver): @ipa-flg-pb `0.6.10-0` indigo: https://github.com/ros/rosdistro/pull/15579 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15580 :white_check_mark:
- [x] [cob_environments](https://github.com/ipa320/cob_environments): @ipa-flg-pb `0.6.5-0` indigo: https://github.com/ros/rosdistro/pull/15545 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15547 :white_check_mark:
- [x] [cob_extern](https://github.com/ipa320/cob_extern): `0.6.11-0` Indigo: https://github.com/ros/rosdistro/pull/15529 :white_check_mark: Kinetic: https://github.com/ros/rosdistro/pull/15530 :white_check_mark: 
- [x] [cob_gazebo_plugins](https://github.com/ipa320/cob_gazebo_plugins): :warning: @ipa-rmb `0.6.6-0, 0.7.1-0` indigo: https://github.com/ros/rosdistro/pull/15537 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15539 :white_check_mark:
- [x] [cob_hand](https://github.com/ipa320/cob_hand): @ipa-flg-pb `0.6.2-0` indigo: https://github.com/ros/rosdistro/pull/15549 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15551 :white_check_mark: 
- [x] [cob_manipulation](https://github.com/ipa320/cob_manipulation):  :warning:  `0.6.5-1` @ipa-rmb indigo: https://github.com/ros/rosdistro/pull/15641 :white_check_mark: kinetic https://github.com/ros/rosdistro/pull/15698 :white_check_mark:
- [x] [cob_navigation](https://github.com/ipa320/cob_navigation): @ipa-flg-pb `0.6.5-0` indigo: https://github.com/ros/rosdistro/pull/15558 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15593 :white_check_mark:
- [x] [cob_perception_common](https://github.com/ipa320/cob_perception_common): @ipa-rmb `0.6.10-0` indigo: https://github.com/ros/rosdistro/pull/15550 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15552 :white_check_mark:
- [x] [cob_robots](https://github.com/ipa320/cob_robots): `0.6.7-1` @ipa-rmb indigo: https://github.com/ros/rosdistro/pull/15646 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15699 :white_check_mark:
- [x] [cob_simulation](https://github.com/ipa320/cob_simulation): `0.6.8-0` @ipa-rmb indigo: https://github.com/ros/rosdistro/pull/15648 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15700 :white_check_mark:
- [x] [cob_substitute](https://github.com/ipa320/cob_substitute): @ipa-flg-pb `0.6.6-0` indigo: https://github.com/ros/rosdistro/pull/15556 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15557 :white_check_mark: 
- [x] [cob_supported_robots](https://github.com/ipa320/cob_supported_robots): @ipa-rmb `0.6.7-0` indigo: https://github.com/ros/rosdistro/pull/15534 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15536 :white_check_mark:
- [x] [schunk_modular_robotics](https://github.com/ipa320/schunk_modular_robotics): @ipa-flg-pb `0.6.9-0` indigo: https://github.com/ros/rosdistro/pull/15533 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15568 :white_check_mark: 
- [x] [sick_visionary_t](https://github.com/SICKAG/sick_visionary_t): @ipa-rmb `0.0.5-0, 0.0.5-1` indigo: https://github.com/ros/rosdistro/pull/15665 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15666 :white_check_mark:
- [x] [universal_robot](https://github.com/ros-industrial/universal_robot): @ipa-fxm `` indigo: https://github.com/ros/rosdistro/pull/15686 :white_check_mark: kinetic: https://github.com/ros/rosdistro/pull/15689 :white_check_mark:
- [ ] [care-o-bot](https://github.com/ipa320/care-o-bot): ``

**Comment by mathias-luedtke** [comment]
`ros_canopen` is released (`0.6.7`/`0.7.5`), do you need a newer version?

**Comment by fmessmer** [comment]
> `ros_canopen` is released (`0.6.7`/`0.7.5`), do you need a newer version?

`ros_canopen` was just mentioned temporarily as we copied the list from last release...we no longer consider `ros_canopen` to be part of the "cob-release-cycle"... the maintainer take care of it very well :wink:

**Comment by mathias-luedtke** [comment]
The fix needed for the raws is not yet released for `indigo`, only for `jade+`

**Comment by fmessmer** [comment]
@ipa-flg-pb @ipa-rmb @ipa-jcl @ipa-fmw 
please continue with the release process for the packages assigned so far....`cob_robots`, `cob_simulation`, `cob_manipulation` and `care-o-bot` are not yet ready for release as we need to clean-up a few things first to make them releasable...
however, they would be released last anyway, as they have the most upstream-dependencies..

once the first PRs to rosdistro have been accepted, please follow [debbuild_indigo](http://repositories.ros.org/status_page/ros_indigo_default.html) and [debbuild_kinetic](http://repositories.ros.org/status_page/ros_kinetic_default.html)

you can tick of the checkbox once indigo and kinetic succeeded, i.e. first two columns are green and last is either blue=OldVersion (indigo) or red=None (kinetic)

post errors from the buildfarm here, if any

**Comment by fmessmer** [comment]
@ipa-flg-pb please come see us about how to proceed with https://github.com/ros/rosdistro/pull/15532#issuecomment-315784794

**Comment by fmessmer** [comment]
@ipa-rmb could you please attach the txt-file with the latest release hints and commands to this issue for the sake of completeness and documentation?

**Comment by ipa-rmb** [comment]
These are the current notes on doing releases:

[release.txt](https://github.com/ipa320/care-o-bot/files/1155579/release.txt)

**Comment by ipa-flg-pb** [comment]
Ther is the following Issue with [`cob_driver/cob_mimic`](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_mimic/package.xml#L22) 
```
Pre-verifying Debian dependency keys...
Running 'rosdep update'...
Key 'python-vlc-pip' resolved to '['python-vlc']' with installer 'pip', which does not match the default installer 'apt'.
Failed to resolve python-vlc-pip on ubuntu:trusty with: Error running generator: The Debian generator does not support dependencies which are installed with the 'pip' installer.
python-vlc-pip is depended on by these packages: ['cob_mimic']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
You can try to address the issues which appear above and try again if you wish.
```
any idea how to solve this?

**Comment by fmessmer** [comment]
@ipa-mdl 
Do you know how to deal with `python-pip` dependencies?
The rosdep key is available [here](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L3431-L3443)

**Comment by mathias-luedtke** [comment]
AFAIR packages with `pip`-only dependencies cannot be released.
Where is this output from?

**Comment by fmessmer** [comment]
it's from `bloom-release <repository_name> --track <track> --rosdistro <distro>` 
(@ipa-flg-pb correct me if I'm wrong)

so, we cannot release `cob_mimic` then?
@ipa-fmw FYI

**Comment by mathias-luedtke** [comment]
https://github.com/ros-infrastructure/bloom/pull/412 might be related

**Comment by mathias-luedtke** [comment]
> so, we cannot release cob_mimic then?

Only if you rewrite it to use `libvlc-dev` directly ;)

**Comment by fmessmer** [comment]
currently having this discussion...
--> https://github.com/ipa320/cob_driver/issues/340

**Comment by mathias-luedtke** [comment]
> The fix needed for the raws is not yet released for indigo, only for jade+

I have made a new release for indigo as well.

**Comment by ipa-rmb** [comment]
Does someone know what causes this error for libconcorde_tsp_solver: http://build.ros.org/job/Kbin_uxhf_uXhf__libconcorde_tsp_solver__ubuntu_xenial_armhf__binary/4/display/redirect

I can find some errors telling it cannot find libqsopt but libqsopt is part of the cob_extern release and there are no errors from the release of libqsopt.

**Comment by mathias-luedtke** [comment]
Is it working for the other architectures?
I would guess that the settings needs to be passed to the `ExternalProject`.

**Comment by ipa-rmb** [comment]
Yes, it works for the other arhcitectures.

The only other which is not working is:
http://build.ros.org/job/Kbin_djv8_dJv8__libconcorde_tsp_solver__debian_jessie_arm64__binary/4/display/redirect

Something was not available for arm, maybe it was libqsopt. However, how does libqsopt then go through smoothly? Or can we turn of arm support?

**Comment by mathias-luedtke** [comment]
>  Or can we turn of arm support?

https://github.com/ros-infrastructure/ros_buildfarm_config/tree/production/kinetic
Please double check for other errors beforehand!

**Comment by fmessmer** [comment]
The release blocker for `cob_manipulation`, i.e. stomp, has been removed in https://github.com/ipa320/cob_manipulation/pull/117 and https://github.com/ipa320/cob_manipulation/pull/119

@ipa-rmb agreed to release the remaining repos `cob_manipulation`, `cob_robots` and `cob_simulation` into both `indigo` and `kinetic` :+1: 

@ipa-flg-pb I consider your job done for the time being...thank you for your help!

**Comment by ipa-rmb** [comment]
I think I figured out how to edit the first message without loosing data:
1. Refresh page
2. Click edit comment but cancel editing immediately (if you would have lost data, it now asks you whether you really want to abort and loose your unsaved changes - click yes)
3. Refresh page
4. Edit the message and save
5. Refresh page

**Comment by fmessmer** [comment]
release of ur_* packages is tracked https://github.com/ros-industrial/universal_robot/issues/240#issuecomment-319575676

**Comment by fmessmer** [comment]
UniversalRobot releases are: 
 - indigo: https://github.com/ros/rosdistro/pull/15686
 - kinetic: https://github.com/ros/rosdistro/pull/15689

**Comment by ipa-rmb** [comment]
Shall we do a release session again or are there some pull requests that we should await first? Do we release care-o-bot as well?

**Comment by fmessmer** [comment]
Yes, we should release care-o-bot, too

For the next cycle, I think we should wait a bit more as there are a few things pending in cob_robots...new bots, zr300 migration, raw3-1 to canopen...

**Comment by ipa-rmb** [comment]
Ok, so care-o-bot should be released already now, the remainder has to wait for the second cycle later, correct?

**Comment by fmessmer** [comment]
:+1:
the next release should also go in a new issue

**Comment by fmessmer** [comment]
Let's just say `care-o-bot` missed one release cycle and close this PR!
We'll trigger a new release some time soon anyway? October?
