### ISSUE TITLE
New maintainers needed!

### ISSUE THREAD

**Issue by mgruhler** [ipa320/care-o-bot#46]
I am the maintainer of the following packages, which I cannot support anymore due to me changing jobs.
Who is willing to take over? (* might also be deleted)

- [ ] cob_common/raw_description
- [ ] cob_control/cob_collision_velocity_filter
- [ ] cob_control/cob_footprint_observer
- [ ] cob_control/cob_omni_drive_controller
- [ ] cob_control/cob_undercarriage_ctrl_node*
- [ ] cob_driver/cob_base_drive_chain*
- [ ] cob_driver/cob_canopen_motor*
- [ ] cob_driver/cob_generic_can*
- [ ] cob_driver/cob_head_axis*
- [ ] cob_driver/cob_undercarriage_ctrl*
- [ ] cob_driver/cob_utilities*
- [ ] cob_driver/cob_voltage_control*

**Comment by floweisshardt** [comment]
I found some more packages which are already or will soon be without maintainer and need somebody to take over. (* might also be deleted)
- [ ] cob_command_tools/cob_interactive_teleop*
- [ ] cob_common/raw_description
- [ ] cob_control/cob_model_identifier*
- [ ] cob_control/cob_omni_drive_controller
- [ ] cob_control/cob_trajectory_controller* --> deleted in https://github.com/ipa320/cob_control/pull/161 and https://github.com/ipa320/cob_robots/pull/695
- [ ] cob_control/cob_twist_controller
- [x] cob_driver/cob_camera_sensors* --> deleted in https://github.com/ipa320/cob_driver/pull/346
- [ ] cob_driver/cob_phidget_em_state
- [ ] cob_driver/cob_phidget_power_state
- [ ] cob_driver/cob_phidgets
- [ ] cob_driver/cob_relayboard* --> deleted in https://github.com/ipa320/cob_robots/pull/696, https://github.com/ipa320/cob_driver/pull/347, https://github.com/ipa320/cob_substitute/pull/46 and https://github.com/ipa320/sick_flexisoft/pull/41
- [ ] cob_driver/cob_scan_unifier
- [ ] cob_extern/libntcan*
- [ ] cob_extern/libpcan*
- [ ] cob_extern/libphidgets
- [ ] cob_manipulation/cob_grasp_generation*
- [ ] cob_manipulation/cob_moveit_bringup
- [ ] cob_manipulation/cob_moveit_interface
- [ ] cob_manipulation/cob_pick_place_action
- [ ] cob_navigation/cob_mapping_slam
- [ ] cob_navigation/cob_navigation_config
- [ ] cob_navigation/cob_navigation_global
- [ ] cob_navigation/cob_navigation_local
- [ ] cob_navigation/cob_navigation_slam
- [ ] schunk_modular_robotics/schunk_description
- [ ] schunk_modular_robotics/schunk_libm5api*
- [ ] schunk_modular_robotics/schunk_powercube_chain*
- [ ] schunk_modular_robotics/schunk_simulated_tactile_sensors
- [ ] schunk_robots/schunk_lwa4d
- [ ] schunk_robots/schunk_lwa4d_moveit_config
- [ ] schunk_robots/schunk_lwa4p
- [ ] schunk_robots/schunk_lwa4p_moveit_config
- [ ] schunk_robots/schunk_pg70
- [ ] schunk_robots/schunk_pw70

**Comment by ipa-rmb** [comment]
Is cob_driver/cob_relayboard not needed anymore? Isn't that a driver used by all rob at work robots?

**Comment by fmessmer** [comment]
as discussed with @ipa-rmb 
let's call a joint meeting and discuss what packages: 
 - really can be removed right away 
 - could made obsolete and removed with some migration effort
 - should be kept but require a change of maintainership

**Comment by ipa-nhg** [comment]
I am also still maintainer of some packages that I can't support anymore.
Looking for a new maintainer for:

- [ ] schunk_modular_robotics (metapackage)
- [ ]  schunk_description
- [ ] cob_supported_robots
- [ ] cob_gazebo_plugins
- [ ] cob_environments (metapackage)
- [ ] cob_default_env_config
- [ ] cob_substitute (metapackage)
- [ ] cob_calibration_data
- [ ] cob_extern (metapackage)
- [ ] cob_default_robot_config
- [ ] cob_bringup
- [ ] cob_robots (metapackage)
- [ ] cob_default_robot_behavior
- [ ] cob_hardware_config
- [ ] cob_hand (metapackage)
- [ ] cob_description
- [ ] cob_common (metapackage)
- [ ] cob_dashboard
- [ ] cob_command_tools (metapackage)
- [ ] cob_teleop
- [ ] cob_control (metapackage)
- [ ] cob_sound
- [ ] cob_mimic
- [ ] cob_driver (metapackage)
- [ ] cob_bringup_sim
- [ ] cob_gazebo
- [ ] cob_gazebo_objects
- [ ] cob_simulation (metapackage)
- [ ] cob_gazebo_worlds

**Comment by fmessmer** [comment]
so, is **every** maintainer now dropping the hot potato?

**Comment by floweisshardt** [comment]
the problem is that there are not so many different maintainers and the above one all will not be at IPA any more soon.

**Comment by fmessmer** [comment]
we discussed the further procedure all together today...I will trigger the next steps to get the maintainers updated asap...

**Comment by fmessmer** [comment]
Maintainers have been updated
Also dependencies to legacy and outdated packages have been removed in ipa320/cob_robots#714

Do we still need to actually remove packages somewhere?
I think we agreed on keeping legacy packages as they do not really harm for the time being? Is this correct?

@ipa-jba @ipa-fez @ipa-rmb @ipa-fmw @ipa-nhg

**Comment by floweisshardt** [comment]
ok for me

**Comment by fmessmer** [comment]
Thus,  I consider this done
