### ISSUE TITLE
How to install the cob_simulator

### ISSUE THREAD

**Issue by jinhooi** [ipa320/care-o-bot#54]
I start to work with care-o-bot4. But I cannot install simulation by "http://wiki.ros.org/Robots/Care-O-bot/indigo" (I have confirmed that it was installed in the last year, but not now.)
So I want to install by cob_simulator but I don't know how to install by cob_simulator in github.
Before I activate the hardware, I want to simulation hard.
I want you to help me simulate.
Thank you.

**Comment by fmessmer** [comment]
problem solved via mail
