### ISSUE TITLE
Kinetic Release 03-2019

### ISSUE THREAD

**Issue by jabbenseth** [ipa320/care-o-bot#55]
previous release: https://github.com/ipa320/care-o-bot/issues/51

`cob_android`: **up-to-date** :point_right: `0.1.4`
`cob_calibration_data`: https://github.com/ros/rosdistro/pull/20565 :point_right: `0.6.10`
`cob_command_tools`: https://github.com/ros/rosdistro/pull/20572 :point_right: `0.6.10`
`cob_common`: **kinetic:** https://github.com/ros/rosdistro/pull/20566, **melodic:** https://github.com/ros/rosdistro/pull/20568  :point_right: `0.6.10`
`cob_control`: https://github.com/ros/rosdistro/pull/20567 :point_right: `0.7.3`
`cob_driver`: https://github.com/ros/rosdistro/pull/20570 :point_right: `0.6.13`
`cob_environments`: https://github.com/ros/rosdistro/pull/20569 :point_right: `0.6.7`
`cob_extern`: **up-to-date** :point_right: `0.6.12`
`cob_gazebo_plugins`: **up-to-date** :point_right: `0.7.2`
`cob_hand`: **up-to-date** :point_right: `0.6.5`
`cob_manipulation`: **up-to-date** :point_right: `0.7.1`
`cob_navigation`: **up-to-date** :point_right: `0.6.7`
`cob_perception_common`: https://github.com/ros/rosdistro/pull/20571 :point_right: `0.6.13`
`cob_robots`: https://github.com/ros/rosdistro/pull/20574 :point_right: `0.6.7`
`cob_simulation`: **up-to-date** :point_right: `0.6.10`
`cob_substitute`: **up-to-date** :point_right: `0.6.7`
`cob_supported_robots`: https://github.com/ros/rosdistro/pull/20573 :point_right: `0.6.10`
`schunk_modular_robotics`: **up-to-date** :point_right: `0.6.12`
~~`sick_visionary_t`:~~
`care-o-bot`: https://github.com/ros/rosdistro/pull/20575 :point_right: `0.6.7`

**Comment by fmessmer** [comment]
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=cob
http://repositories.ros.org/status_page/ros_melodic_default.html?q=cob

**Comment by fmessmer** [comment]
the kinetic release has been synced
