### ISSUE TITLE
Migration to package format 2

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/care-o-bot#7]
@ipa-fmw @ipa-nhg @ipa-mdl @ipa-mig @ipa-rmb @ipa-bnm

https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Aipa320+Migration+package+format+2

Let's use this Issue for general discussion about what's still missing for a successfull migration to package format 2:

Remaining repos to be migrated:
 - cob_extern
 - cob_perception_common
 - cob_perception_data
 - cob_navigation
 - cob_android
 - care-o-bot (this package)
 - ...

Remaining decisions to be applied wherever it occurs:
 - Are we going to install headers for "executable-only" packages?
 - ...

Please contribute to the discussion in case something is not yet mentioned here...

**Comment by ipa-mdl** [comment]
+1 for not installing headers for"executable-only" packages

**Comment by ipa-mdl** [comment]
* tests and roslaunch checks, test_depends

**Comment by ipa-mig** [comment]
+1 for not installing headers of "executable-only" packages.

**Comment by ipa-mig** [comment]
How should boost dependencies be handled?
`find_package` it when used directly, maybe with `COMPONENTS REQUIRED`?
How should it be in the `package.xml`?

**Comment by ipa-bnm** [comment]
+1 for not installing headers of "executable-only" packages

**Comment by ipa-fxm** [comment]
I'd suggest to be consequent and add explicit dependencies for boost!
I also already started to clean-up executable-only packages (see [cob_command_tools](https://github.com/ipa-fxm/cob_command_tools/commit/efad34046c416884d9306be3bc8b374ae5faf0b5))

**Comment by ipa-fxm** [comment]
Also, how about packages where there are libraries?
In case the libraries are only used within the same packages, they do not need to be exported, right?

This would mean: 
 - no install tag for the library?
 - no install tags for the headers used in the library?
 - no LIBRARIES in catkin_package?
 - no INCLUDE_DIRS in catkin_package?
 - thus, also no CATKIN_DEPENS and DEPENDS required?
Is this correct?

How about libraries, that are used by other packages, e.g. `cob_generic_can` or `cob_canopen_motor`?
 - install library!
 - export LIBRARIES in catkin_package!
 - install headers, too?

What about plugins?

@ipa-mdl could you bring in some light here?

**Comment by ipa-fxm** [comment]
I'd postpone reviewing "everything-tests-related" to the new issue #8

**Comment by ipa-fxm** [comment]
What are we going to to about tags like this (e.g. from [here](https://github.com/ipa320/cob_control/blob/indigo_dev/cob_base_velocity_smoother/CMakeLists.txt#L6-L10)):
```
if(CMAKE_COMPILER_IS_GNUCXX)
  add_definitions(-std=gnu++0x)
else()
  add_definitions(-std=c++0x)
endif()
```

**Comment by ipa-mdl** [comment]
You are right with the libraries.
Plug-in has to be built and installed, headers are not needed. And the plugin xml has to be installed, of cause.

C++11 code should be avoided for now if possible.
I had a brief look at `cob_base_velocity_smoother`, I think it does not need c++11.

C++11 is will be okay for executables, but probabably not for library, since the the c++11 must be passed to dependent packages and I do not know if this works.

**Comment by ipa-mig** [comment]
So we have to decide how to handle the libraries, right?
IMO, installing libraries and headers will allow other people to use this functionality.
Will also make things easier, if someone from IPA starts working on a node using a library, that is in another package.

So my vote is for installing (generally) installing libraries and headers with the respective `CATKIN_DEPEND` with the exception of where it will definitely not be used somewhere else (e.g. `cob_undercarriage_ctrl` due to getting deprecated)

**Comment by ipa-mig** [comment]
So boost should only be addes as dependency, when any boost header is explicitely included. right?

**Comment by ipa-mdl** [comment]
Boost should be added at least if certain components are used (system, threads, file_system).

If the libs should be use elswhere (i.e. are useful for others, too) they should be installed.
Each lib needs its headers  installed!

**Comment by ipa-fxm** [comment]
So most of the packages have been migrated and merged!

 > Remaining repos to be migrated:
 - cob_extern
 - cob_perception_common
 - cob_perception_data
 - cob_navigation
 - cob_android
 - care-o-bot (this package)
 - ...

@ipa-fmw @ipa-nhg @ipa-mdl @ipa-mig @ipa-rmb @ipa-bnm
So, who is volunteering to migrate the packages above?

**Comment by ipa-mig** [comment]
I'll take over `cob_navigation`. And I can also do `cob_extern`.

**Comment by ipa-bnm** [comment]
i take cob_android

**Comment by ipa-nhg** [comment]
I take care-o-bot and cob_test_robots

**Comment by ipa-bnm** [comment]
and my votes
libraries:
- always install libraries with their headers even if the lib is only used inside the same package for the moment
- generally export libraries and headers in catkin_package

plugins:
- as mdl already wrote. Install plugin.xml and the lib. No need for headers!

boost:
- i think boost depends are only needed if certain non header-only libs are used. Here a list of boost libs that require building:
Boost.Chrono,
Boost.Context,
Boost.Filesystem,
Boost.GraphParallel,
Boost.IOStreams,
Boost.Locale,
Boost.MPI,
Boost.ProgramOptions,
Boost.Python,
Boost.Regex,
Boost.Serialization,
Boost.Signals,
Boost.System,
Boost.Thread,
Boost.Timer,
Boost.Wave

**Comment by ipa-fxm** [comment]
@ipa-bnm 
That's the way it has been done now for the packages that are already migrated....

**Comment by ipa-mig** [comment]
ipa320/cob_navigation#50 and ipa320/cob_extern#48 done.

**Comment by ipa-fxm** [comment]
Awesome
:+1:

**Comment by ipa-fxm** [comment]
I'll start triggering new releases...later the day/evening...

**Comment by ipa-mig** [comment]
I’d like to do this for cob_navigation as well.
Can you maybe show me how to do this some time this/next week?

Von: Felix Messmer [mailto:notifications@github.com]
Gesendet: Dienstag, 25. August 2015 14:45
An: ipa320/care-o-bot
Cc: Gruhler, Matthias
Betreff: Re: [care-o-bot] Migration to package format 2 (#7)


I'll start triggering new releases...later the day/evening...

**Comment by ipa-fxm** [comment]
New Releases triggered:
 - cob_extern: https://github.com/ros/rosdistro/pull/9277

**Comment by ipa-fxm** [comment]
I decided to go on with the rest of the repositories...
...as releasing can easily be done, we could release in shorter cycles whenever a new fix is introduced within one of the repos!

**Comment by ipa-fxm** [comment]
All :green_heart:

**Comment by ipa-mig** [comment]
:clap:

**Comment by ipa-fmw** [comment]
schunk_robots will not be released
